../paper/relmse_var.eps: plot_rrmse.R
	R CMD BATCH plot_rrmse.R

../paper/relmse2_prec.eps: plot_rrmse.R
	R CMD BATCH plot_rrmse.R

../paper/rmse_gtex.eps: plot_rrmse_gtex.R
	R CMD BATCH plot_rrmse_gtex.R

../paper/tissuepairs.eps: choose_tissue_pair.R
	R CMD BATCH choose_tissue_pair.R